# Example
# Please note that it will not work as it is!
version: '3'

services:
  server:
    container_name: sample-server
    image: sample
    restart: always
    environment:
      - VIRTUAL_HOST="sample.com"
      - VIRTUAL_PORT=9000
      # Settings for Let's Encrypt.
      - LETSENCRYPT_HOST="sample.com"
      - LETSENCRYPT_EMAIL="sample@example.com"
    networks:
      - sample

  nginx:
    container_name: sample-nginx
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    depends_on:
      - server
    networks:
      - sample

  lets-encrypt:
    container_name: sample-lets-encrypt
    build: .
    restart: always
    environment:
      # Find nginx proxy container.
      - NGINX_PROXY_CONTAINER=sample-nginx
      - NGINX_DOCKER_GEN_CONTAINER=sample-nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Please set google.json for dns admin service account
      # Ref. https://cloud.google.com/iam/docs/creating-managing-service-accounts?hl=en
      - ./google.json:/root/.secrets/certbot/google.json
      - letsencrypt-pem:/etc/letsencrypt:rw
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    depends_on:
      - nginx
    networks:
      - sample

networks:
  sample:
    driver: bridge

volumes:
  letsencrypt-pem:
  nginx-certs:
  nginx-vhost:
  nginx-html:
